### ISSUE TITLE
Need Mathjax Block support on Front/Back notes

### ISSUE THREAD

**Issue by tenheadedlion** [lazy-void/inka#23]
Hello, thanks for the project!

I tried Mathjax block in front/back notes and saw Anki desktop didn't render the right symbols:

In the markdown I wrote:

```markdown
1. MathTest1

> $X^{2}$

2. MathTest2

> $$
> X^{2}
> $$
```

Anki desktop rendered `MathTest1` rightly,  the Back textbox of the Anki Browse showed the following content:

```
\(X^{2}\)
```

As with `MathTest2`, Anki desktop showed `X^{2}` with this block on the textbox:

```
\(\)

X^{2}

\(\)
```

After I modified the textbox as follows, Anki rendered it rightly:

```
\(
x^{2}
\)
```

By the way, this is a very good tool!

**Comment by lazy-void** [comment]
Hi, thanks for the bug report and kind words. I will try to fix this shortly.

**Comment by lazy-void** [comment]
Fixed it in the new release. You need to upgrade your version with `pip install --upgrade inka`.

**Comment by tenheadedlion** [comment]
@lazy-void I updated and it works nicely. Thanks for fixing this!
