### ISSUE TITLE
Should each answer line start with >?

### ISSUE THREAD

**Issue by Positron010** [lazy-void/inka#4]
Hi,
In the documentation it is stated that answers start by >, but should each new line in the answer contain > as a start. To be more clear is the following answer accepted?

1. Question

">" Answer
New line of answer

Or it should be like this?

1. Question

">" Answer
">" New line of answer

Note: the quotes around > are just to prevent it of acting as blockquotes.

**Comment by lazy-void** [comment]
Last one. You should prefix each new line with `>` symbol. As an example from my own notes:

```markdown
11. What **scopes** are there in *Python*?

> - *Local* - inside a function
> - *Enclosed* - inside an enclosing function
> - *Global* - on a module level
> - *Built-in* - names from a special module *builtins*
>
> **INDENTATION DOESN'T AFFECT SCOPE (for, while, if...)**
```

**Comment by Positron010** [comment]
Alright! Thanks for replying @lazy-void !
